/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
     // Definición de coeficientes
    val a = 2.0
    val b = -4.0
    val c = 1.5

    // Validación: 'a' no debe ser cero
    if (a == 0.0) {
        println("El coeficiente 'a' no puede ser cero en una función cuadrática.")
        return
    }

    // Mostrar la función en formato ax² + bx + c
    println("La función cuadrática es: ${formatoFuncionCuadratica(a, b, c)}")
}

// Función para mostrar la ecuación en formato ax² + bx + c
fun formatoFuncionCuadratica(a: Double, b: Double, c: Double): String {
    fun coefToStr(coef: Double, variable: String): String {
        return when {
            coef == 0.0 -> ""
            coef == 1.0 -> "+$variable"
            coef == -1.0 -> "-$variable"
            coef > 0 -> "+${coef}$variable"
            else -> "${coef}$variable"
        }
    }

    val termA = "${a}x²"
    val termB = coefToStr(b, "x")
    val termC = if (c > 0) "+$c" else "$c"

    return "$termA$termB$termC"
    println(App().greeting)
}



