/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
un main() {
    val a = 4
    val b = 6
    val c = -9    if (a == 0) {
        println("El coeficiente 'a' no puede ser cero.")
        return
    }    val funcion = buildString {
        append("${a}x² ")
        append(if (b >= 0) "+ $b" else "- ${-b}")
        append("x ")
        append(if (c >= 0) "+ $c" else "- ${-c}")
    }
    println(App().greeting)
}



